name: Build & Sign Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install MAUI workload
      run: dotnet workload install maui-android

    - name: Generate signing keystore
      run: |
        keytool -genkeypair -v -keystore ahlawy-store.keystore -alias ahlawy -keyalg RSA -keysize 2048 -validity 10000 -storepass ahlawy123 -keypass ahlawy123 -dname "CN=Ahlawy-Store, OU=Dev, O=Ahlawy-Store, L=Cairo, ST=Cairo, C=EG"

    - name: Copy keystore to project
      run: Copy-Item ahlawy-store.keystore PS5PayloadSender/ahlawy-store.keystore

    - name: Restore dependencies
      run: dotnet restore PS5PayloadSender/PS5PayloadSender.csproj

    - name: Build APK (Release - Auto Signed)
      run: dotnet build PS5PayloadSender/PS5PayloadSender.csproj -f net10.0-android -c Release -o ./output

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ahlawy-Store-APK
        path: ./output/**/*.apk
        if-no-files-found: warn