name: Build Ahlawy-Store Host

on:
  push:
    branches: [ "main" ]
    paths:
      - "PS5Host/**"
      - ".github/workflows/host.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install PS5 toolchain
      run: |
        wget -q https://github.com/ps5-payload-dev/pacbrew-repo/releases/latest/download/ps5-payload-dev.tar.gz
        sudo tar xf ps5-payload-dev.tar.gz -C /

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      working-directory: PS5Host
      run: |
        make clean all PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk

    - name: Upload ELF artifact
      uses: actions/upload-artifact@v4
      with:
        name: ahlawy-host-elf
        path: PS5Host/ahlawy-host.elf
        if-no-files-found: error
